name = "Kitsune Client"
author = "Kitsune"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d17e2e7ba9f64630e52329dac63a2281ed69bc3bcae7e976cc8ee663f59884f"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.17"
