name = "Kitsune Client"
author = "Kitsune"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20628a226956041c48d183953e72a743765844bf481ebabbc661ed83c4140452"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.17"
