name = "Kitsune Client"
author = "Kitsune"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58df4eaf9883ca08fe05a0973a9d75da9ef42bca97032ccd193b10c46f577aa9"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.17"
