name = "Kitsune Client"
author = "Kitsune"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be55c71e975d15fafdb3792475888203cf2f67b53e4f4c63a8a0e022a696aac3"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.17"
